apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebom-backend
  namespace: default
  labels:
    name: rebom-backend
    app: rebom
    {{- include "rebom.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebom
      name: rebom-backend
      {{- include "rebom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: rebom-backend
        app: rebom
        {{- include "rebom.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: rebom-backend-container
        image: registry.relizahub.com/library/rebom-backend
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: password
        ports:
        - containerPort: 4000
      initContainers:
      - name: rebom-backend-init
        image: registry.relizahub.com/library/rebom-backend
        command: ["cp", "-r", "/app/migrations/.", "/flyway/sql"]
        volumeMounts:
        - mountPath: /flyway/sql
          name: migrations-sql
      - name: rebom-backend-migrations
        image: flyway/flyway:8.4.4-alpine
        env:
        - name: POSTGRES_JDBC
          value: jdbc:postgresql://postgres:5432/postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: password
        command: ['/bin/sh', '-c', "/flyway/flyway -url=$POSTGRES_JDBC -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -defaultSchema=rebom -schemas=rebom migrate"]
        volumeMounts:
          - mountPath: "/flyway/sql"
            name: migrations-sql
      volumes:
        - name: migrations-sql
          emptyDir: {}