apiVersion: v1
kind: Service
metadata:
  name: rebom-frontend-service
  namespace: default
  labels:
    {{- include "rebom.labels" . | nindent 4 }}
spec:
  selector:
    app: rebom
    name: rebom-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80