apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebom-frontend
  namespace: default
  labels:
    name: rebom-frontend
    app: rebom
    {{- include "rebom.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebom
      name: rebom-frontend
      {{- include "rebom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: rebom-frontend
        app: rebom
        {{- include "rebom.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: rebom-frontend
        image: registry.relizahub.com/library/rebom-frontend
        env:
        - name: BACKEND_HOST
          value: rebom-backend-service
        - name: BACKEND_PORT
          value: "4000"
        ports:
        - containerPort: 80