apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgpassword
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rebom.labels" . | nindent 4 }}
type: Opaque
data:
  password: cGFzc3dvcmQ=